import 'package:flutter/material.dart';
import '../../core/theme/app_theme.dart';
import '../../core/widgets/app_widgets.dart';
import '../../core/widgets/animateur_shell.dart';
import 'animateur_live_screen.dart';

class AnimateurDashboardScreen extends StatelessWidget {const AnimateurDashboardScreen({super.key});@override Widget build(BuildContext context)=>const AnimateurShell();}

class AnimateurDashboardContent extends StatelessWidget {const AnimateurDashboardContent({super.key});@override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(20),children:[const Text('Bonjour Edith',style:TextStyle(fontSize:28,fontWeight:FontWeight.w800,color:AppColors.ink)),const SizedBox(height:5),const Text('Votre prochaine intervention est prête.',style:TextStyle(color:AppColors.muted)),const SizedBox(height:20),I24HCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('PROCHAINE ÉMISSION',style:TextStyle(fontSize:11,fontWeight:FontWeight.w800,color:AppColors.gold,letterSpacing:1)),SizedBox(height:5),Text('Le Grand Direct',style:TextStyle(fontSize:22,fontWeight:FontWeight.w800,color:AppColors.ink)),SizedBox(height:4),Text('14:00 — 18:00 · Studio A',style:TextStyle(color:AppColors.muted,fontSize:12))])),Container(width:46,height:46,decoration:BoxDecoration(color:AppColors.navy,borderRadius:BorderRadius.circular(14)),child:const Icon(Icons.mic,color:Colors.white))]),const SizedBox(height:16),Row(children:[Expanded(child:FilledButton.icon(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const AnimateurLiveScreen())),icon:const Icon(Icons.mic_none),label:const Text('Ouvrir le studio'))),const SizedBox(width:9),Expanded(child:OutlinedButton.icon(onPressed:()=>ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Planning ouvert'))),icon:const Icon(Icons.calendar_month_outlined),label:const Text('Planning')))])])),const SizedBox(height:20),const SectionTitle(title:'État du studio'),Row(children:[Expanded(child:const StatCard(value:'Stable',label:'Connexion',icon:Icons.wifi_rounded)),const SizedBox(width:10),Expanded(child:const StatCard(value:'−12 dB',label:'Microphone',icon:Icons.mic_none_rounded))]),const SizedBox(height:20),const SectionTitle(title:'À faire'),...['Vérifier le conducteur de l’émission','Préparer le lancement du direct','Relire les intentions reçues'].map((x)=>Padding(padding:const EdgeInsets.only(bottom:9),child:I24HCard(child:Row(children:[const Icon(Icons.check_box_outline_blank,color:AppColors.navy),const SizedBox(width:12),Expanded(child:Text(x,style:const TextStyle(fontWeight:FontWeight.w600,color:AppColors.ink))),const Icon(Icons.chevron_right_rounded,color:AppColors.muted)]))))]);}
